apiVersion: v1
kind: Pod
metadata:
  name: model-guard-pod
  labels:
    app: model-guard-cluster
spec:
  volumes:
    - name: postgres-storage
      emptyDir: {}

  containers:
    #СУБД (PostgreSQL) — Изолированный порт данных
    - name: db
      image: postgres:15-alpine
      env:
        - name: POSTGRES_DB
          value: "model_guard_db"
        - name: POSTGRES_USER
          value: "db_user"
        - name: POSTGRES_PASSWORD
          value: "db_password"
      ports:
        - containerPort: 5432
      volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data

    #Веб-приложение (Django) — Взаимодействие через локальный интерфейс
    - name: web
      image: model-guard-app:latest
      imagePullPolicy: IfNotPresent
      env:
        - name: SECRET_KEY_ML
          value: "ModelGuard_Secret_Salt"
        - name: DEBUG
          value: "True"
        - name: DB_NAME
          value: "model_guard_db"
        - name: DB_USER
          value: "db_user"
        - name: DB_PASSWORD
          value: "db_password"
        - name: DB_HOST
          value: "127.0.0.1"  # Внутри одного пода контейнеры делят localhost
        - name: DB_PORT
          value: "5432"
      ports:
        - containerPort: 8000

    # Маршрутизатор трафика (Nginx) — Внешний контур
    - name: nginx
      image: nginx:alpine
      ports:
        - containerPort: 80

    # Система мониторинга параметров качества (Prometheus)
    - name: prometheus
      image: prom/prometheus:latest
      ports:
        - containerPort: 9090